import type { ImageSource } from "expo-image";

export interface ArtHitBox {
  /** Pixel dimensions of the source image before Expo applies contentFit. */
  size: { width: number; height: number };
  /** Opaque bounds in source-image pixels (transparent padding is excluded). */
  opaqueBounds: { x: number; y: number; width: number; height: number };
}

// Art registry: maps a catalog item id to its bundled image asset. Kept out of
// the domain (which stays art-free) and out of the catalog (which stays semantic
// tags only) so presentation can evolve independently. The tiles are placeholder
// duotone images generated by ../../../scripts/gen-studio-placeholders.mjs;
// replace a file in assets/studio/ with real art and it flows through unchanged.
// An id with no entry falls back to the labelled colored block (see spot-layer).

const ART: Record<string, ImageSource> = {
  // 1. Hero Video Zone
  "big-screen": require("../../../../assets/studio/big-screen.png"),
  "big-screen-2": require("../../../../assets/studio/big-screen-2.png"),
  "led-wall": require("../../../../assets/studio/led-wall.png"),
  // 2. Preview Zone
  "preview-screen": require("../../../../assets/studio/preview-screen.png"),
  "preview-screen-2": require("../../../../assets/studio/preview-screen-2.png"),
  // 3. Tall Module
  locker: require("../../../../assets/studio/locker.png"),
  "shoe-rack": require("../../../../assets/studio/shoe-rack.png"),
  "costume-rack": require("../../../../assets/studio/costume-rack.png"),
  "snack-bar": require("../../../../assets/studio/snack-bar.png"),
  trophy: require("../../../../assets/studio/trophy.png"),
  "trophy-2": require("../../../../assets/studio/trophy-2.png"),
  // 4. Low Module
  "dj-booth": require("../../../../assets/studio/dj-booth.png"),
  speaker: require("../../../../assets/studio/speaker.png"),
  boombox: require("../../../../assets/studio/boombox.png"),
  "boombox-2": require("../../../../assets/studio/boombox-2.png"),
  storage: require("../../../../assets/studio/storage.png"),
  // 5. Lounge Kit
  sofa: require("../../../../assets/studio/sofa.png"),
  "sofa-2": require("../../../../assets/studio/sofa-2.png"),
  "coffee-table": require("../../../../assets/studio/coffee-table.png"),
  pouf: require("../../../../assets/studio/pouf.png"),
  // 6. Ceiling
  spotlight: require("../../../../assets/studio/spotlight.png"),
  "spotlight-2": require("../../../../assets/studio/spotlight-2.png"),
  "disco-ball": require("../../../../assets/studio/disco-ball.png"),
  "neon-ring": require("../../../../assets/studio/neon-ring.png"),
  // 7. Floor Module
  rug: require("../../../../assets/studio/rug.png"),
  stage: require("../../../../assets/studio/stage.png"),
  "stage-2": require("../../../../assets/studio/stage-2.png"),
  "dance-mat": require("../../../../assets/studio/dance-mat.png"),
  "neon-circle": require("../../../../assets/studio/neon-circle.png"),
  // 8. Wall Art
  poster: require("../../../../assets/studio/poster.png"),
  mirror: require("../../../../assets/studio/mirror.png"),
  "mirror-2": require("../../../../assets/studio/mirror-2.png"),
  "neon-sign": require("../../../../assets/studio/neon-sign.png"),
  moodboard: require("../../../../assets/studio/moodboard.png"),
  // 9. Small Decor
  plant: require("../../../../assets/studio/plant.png"),
  "plant-2": require("../../../../assets/studio/plant-2.png"),
  skateboard: require("../../../../assets/studio/skateboard.png"),
  basketball: require("../../../../assets/studio/basketball.png"),
  "water-bottle": require("../../../../assets/studio/water-bottle.png"),
};

// The generated studio assets intentionally retain transparent padding for
// composition. Rendering needs that padding; hit testing must not treat it as
// part of the furniture. These bounds were measured from each asset's alpha
// channel (with a small margin retained for soft shadows).
const ART_HIT_BOXES: Record<string, ArtHitBox> = {
  "big-screen": { size: { width: 623, height: 1288 }, opaqueBounds: { x: 8, y: 4, width: 608, height: 1280 } },
  "big-screen-2": { size: { width: 623, height: 1288 }, opaqueBounds: { x: 8, y: 4, width: 608, height: 1280 } },
  boombox: { size: { width: 864, height: 703 }, opaqueBounds: { x: 52, y: 130, width: 800, height: 560 } },
  "boombox-2": { size: { width: 1024, height: 1024 }, opaqueBounds: { x: 228, y: 86, width: 592, height: 832 } },
  mirror: { size: { width: 388, height: 1229 }, opaqueBounds: { x: 30, y: 10, width: 352, height: 1152 } },
  "mirror-2": { size: { width: 1024, height: 1536 }, opaqueBounds: { x: 358, y: 298, width: 304, height: 928 } },
  plant: { size: { width: 645, height: 785 }, opaqueBounds: { x: 64, y: 44, width: 544, height: 720 } },
  "plant-2": { size: { width: 1024, height: 1024 }, opaqueBounds: { x: 296, y: 74, width: 448, height: 864 } },
  "preview-screen": { size: { width: 640, height: 1358 }, opaqueBounds: { x: 8, y: 28, width: 624, height: 1296 } },
  "preview-screen-2": { size: { width: 640, height: 1358 }, opaqueBounds: { x: 8, y: 28, width: 624, height: 1296 } },
  sofa: { size: { width: 857, height: 725 }, opaqueBounds: { x: 52, y: 10, width: 768, height: 672 } },
  "sofa-2": { size: { width: 1024, height: 1024 }, opaqueBounds: { x: 68, y: 294, width: 896, height: 496 } },
  spotlight: { size: { width: 1336, height: 871 }, opaqueBounds: { x: 48, y: 22, width: 1216, height: 704 } },
  "spotlight-2": { size: { width: 1024, height: 1024 }, opaqueBounds: { x: 312, y: 126, width: 400, height: 592 } },
  stage: { size: { width: 933, height: 1024 }, opaqueBounds: { x: 2, y: 442, width: 896, height: 384 } },
  "stage-2": { size: { width: 1024, height: 1024 }, opaqueBounds: { x: 48, y: 236, width: 928, height: 608 } },
  trophy: { size: { width: 546, height: 1452 }, opaqueBounds: { x: 74, y: 34, width: 416, height: 1392 } },
  "trophy-2": { size: { width: 1024, height: 1536 }, opaqueBounds: { x: 288, y: 96, width: 432, height: 1264 } },
};

/** The bundled art for a catalog item, or null if it has none yet. */
export function artSource(id: string): ImageSource | null {
  return ART[id] ?? null;
}

/** The visible, non-transparent portion of an item asset, if it has one. */
export function artHitBox(id: string): ArtHitBox | null {
  return ART_HIT_BOXES[id] ?? null;
}
