import type { ImageSource } from "expo-image";

// Art registry: maps a catalog item id to its bundled image asset. Kept out of
// the domain (which stays art-free) and out of the catalog (which stays semantic
// tags only) so presentation can evolve independently. The tiles are placeholder
// duotone images generated by ../../../scripts/gen-studio-placeholders.mjs;
// replace a file in assets/studio/ with real art and it flows through unchanged.
// An id with no entry falls back to the labelled colored block (see spot-layer).

const ART: Record<string, ImageSource> = {
  rug: require("../../../../assets/studio/rug.png"),
  stage: require("../../../../assets/studio/stage.png"),
  "dance-mat": require("../../../../assets/studio/dance-mat.png"),
  poster: require("../../../../assets/studio/poster.png"),
  mirror: require("../../../../assets/studio/mirror.png"),
  "big-screen": require("../../../../assets/studio/big-screen.png"),
  "led-wall": require("../../../../assets/studio/led-wall.png"),
  spotlight: require("../../../../assets/studio/spotlight.png"),
  "disco-ball": require("../../../../assets/studio/disco-ball.png"),
  "neon-ring": require("../../../../assets/studio/neon-ring.png"),
  plant: require("../../../../assets/studio/plant.png"),
  trophy: require("../../../../assets/studio/trophy.png"),
  speaker: require("../../../../assets/studio/speaker.png"),
  boombox: require("../../../../assets/studio/boombox.png"),
};

/** The bundled art for a catalog item, or null if it has none yet. */
export function artSource(id: string): ImageSource | null {
  return ART[id] ?? null;
}
