-- Admin-managed studio catalog. All reads and writes go through the server's
-- secret-key client; RLS is enabled without client policies intentionally.
create table public.catalog_items (
  id text primary key,
  tags jsonb not null,
  display_name text not null,
  art_url text,
  art_hitbox jsonb,
  blurhash text,
  status text not null default 'draft',
  access text not null default 'free',
  price integer,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint catalog_items_id_slug_check
    check (id ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
  constraint catalog_items_tags_object_check
    check (jsonb_typeof(tags) = 'object'),
  constraint catalog_items_status_check
    check (status in ('draft', 'published')),
  constraint catalog_items_access_check
    check (access in ('free', 'premium')),
  constraint catalog_items_price_check
    check (price is null or price >= 0)
);

create index catalog_items_status_sort_order_idx
  on public.catalog_items (status, sort_order);

alter table public.catalog_items enable row level security;

create trigger catalog_items_set_updated_at
  before update on public.catalog_items
  for each row execute procedure public.set_updated_at();

-- The fixed id/check constraint keeps this table to exactly one version row.
create table public.catalog_meta (
  id smallint primary key default 1,
  version bigint not null default 0,
  constraint catalog_meta_single_row_check check (id = 1)
);

alter table public.catalog_meta enable row level security;

insert into public.catalog_meta (id, version) values (1, 0);

create function public.bump_catalog_version()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  update public.catalog_meta
  set version = version + 1
  where id = 1;
  return null;
end;
$$;

-- One bump per mutating statement is sufficient to invalidate every replica's
-- catalog cache, including after deletes where max(updated_at) cannot change.
create trigger catalog_items_bump_version
  after insert or update or delete on public.catalog_items
  for each statement execute procedure public.bump_catalog_version();

-- Generated by scripts/generate-catalog-seed.mjs from studio-core CATALOG and
-- defaultItemLabel. Do not hand-edit these rows; rerun the generator instead.
insert into public.catalog_items (id, tags, display_name, status, access)
values
  ('big-screen', '{"type":"video","size":"L"}'::jsonb, 'Big Screen', 'published', 'free'),
  ('big-screen-2', '{"type":"video","size":"L"}'::jsonb, 'Big Screen 2', 'published', 'free'),
  ('led-wall', '{"type":"video","size":"L"}'::jsonb, 'Led Wall', 'published', 'free'),
  ('preview-screen', '{"type":"preview","size":"S"}'::jsonb, 'Preview Screen', 'published', 'free'),
  ('preview-screen-2', '{"type":"preview","size":"S"}'::jsonb, 'Preview Screen 2', 'published', 'free'),
  ('locker', '{"type":"tall","size":"L"}'::jsonb, 'Locker', 'published', 'free'),
  ('shoe-rack', '{"type":"tall","size":"L"}'::jsonb, 'Shoe Rack', 'published', 'free'),
  ('costume-rack', '{"type":"tall","size":"L"}'::jsonb, 'Costume Rack', 'published', 'free'),
  ('snack-bar', '{"type":"tall","size":"L"}'::jsonb, 'Snack Bar', 'published', 'free'),
  ('trophy', '{"type":"tall","size":"L"}'::jsonb, 'Trophy', 'published', 'free'),
  ('trophy-2', '{"type":"tall","size":"L"}'::jsonb, 'Trophy 2', 'published', 'free'),
  ('dj-booth', '{"type":"low","size":"M"}'::jsonb, 'Dj Booth', 'published', 'free'),
  ('speaker', '{"type":"low","size":"M"}'::jsonb, 'Speaker', 'published', 'free'),
  ('boombox', '{"type":"low","size":"M"}'::jsonb, 'Boombox', 'published', 'free'),
  ('boombox-2', '{"type":"low","size":"M"}'::jsonb, 'Boombox 2', 'published', 'free'),
  ('storage', '{"type":"low","size":"M"}'::jsonb, 'Storage', 'published', 'free'),
  ('sofa', '{"type":"lounge"}'::jsonb, 'Sofa', 'published', 'free'),
  ('sofa-2', '{"type":"lounge"}'::jsonb, 'Sofa 2', 'published', 'free'),
  ('coffee-table', '{"type":"lounge"}'::jsonb, 'Coffee Table', 'published', 'free'),
  ('pouf', '{"type":"lounge"}'::jsonb, 'Pouf', 'published', 'free'),
  ('spotlight', '{"type":"ceiling"}'::jsonb, 'Spotlight', 'published', 'free'),
  ('spotlight-2', '{"type":"ceiling"}'::jsonb, 'Spotlight 2', 'published', 'free'),
  ('disco-ball', '{"type":"ceiling"}'::jsonb, 'Disco Ball', 'published', 'free'),
  ('neon-ring', '{"type":"ceiling"}'::jsonb, 'Neon Ring', 'published', 'free'),
  ('rug', '{"type":"floor","size":"L"}'::jsonb, 'Rug', 'published', 'free'),
  ('stage', '{"type":"floor","size":"L"}'::jsonb, 'Stage', 'published', 'free'),
  ('stage-2', '{"type":"floor","size":"L"}'::jsonb, 'Stage 2', 'published', 'free'),
  ('dance-mat', '{"type":"floor","size":"L"}'::jsonb, 'Dance Mat', 'published', 'free'),
  ('neon-circle', '{"type":"floor","size":"L"}'::jsonb, 'Neon Circle', 'published', 'free'),
  ('poster', '{"type":"wall","size":"M"}'::jsonb, 'Poster', 'published', 'free'),
  ('mirror', '{"type":"wall","size":"M"}'::jsonb, 'Mirror', 'published', 'free'),
  ('mirror-2', '{"type":"wall","size":"M"}'::jsonb, 'Mirror 2', 'published', 'free'),
  ('neon-sign', '{"type":"wall","size":"M"}'::jsonb, 'Neon Sign', 'published', 'free'),
  ('moodboard', '{"type":"wall","size":"M"}'::jsonb, 'Moodboard', 'published', 'free'),
  ('plant', '{"type":"decor","size":"S"}'::jsonb, 'Plant', 'published', 'free'),
  ('plant-2', '{"type":"decor","size":"S"}'::jsonb, 'Plant 2', 'published', 'free'),
  ('skateboard', '{"type":"decor","size":"S"}'::jsonb, 'Skateboard', 'published', 'free'),
  ('basketball', '{"type":"decor","size":"S"}'::jsonb, 'Basketball', 'published', 'free'),
  ('water-bottle', '{"type":"decor","size":"S"}'::jsonb, 'Water Bottle', 'published', 'free')
on conflict (id) do nothing;
